### PR TITLE
BLD: switch to Cython 3.0, forbid deprecated Numpy C API in generated code

### PR DESCRIPTION
**Pull request by neutrinoceros**

### CODE REVIEW

**Comment by matthewturk** [comment]
my guess is that we'll see pretty enormous performance regressions here if we aren't careful

**Comment by neutrinoceros** [comment]
Yes, that's what I'm worried about too. Is there a way to test for it that doesn't involve running yt's test suite ?
Maybe we could just systematically change `nogil` into `noexcept nogil` ?

**Comment by matthewturk** [comment]
I think that's a good idea.  It might be sufficient just to do some SPH queries with this to demonstrate the slowndown; I bet they will show up in larger runs, but not smaller ones.

**Comment by neutrinoceros** [comment]
Actually `nogil` only show up on one line
https://github.com/yt-project/ewah_bool_utils/blob/36a0072ade35769f731caf814477b284db6a0192/ewah_bool_utils/ewah_bool_wrap.pyx#L23-L24

I confess I do not understand this definition. Is it critical ?

**Comment by neutrinoceros** [comment]
ping @matthewturk

**Review by matthewturk — APPROVED** [review]

**Pull request merged**
