### PR TITLE
BLD: migrate to src layout

### PR DESCRIPTION
**Pull request by neutrinoceros**
This prevents accidentally validating code that only works when installed in editable mode.

### CODE REVIEW

**Comment by matthewturk** [comment]
This needs more discussion, so hold off on merging.

**Comment by matthewturk** [comment]
I think that the main issue I have is that while we might make this change going forward, it is also a bit of a solution in search of a problem to apply it to existing repositories.  I think the one issue was addressed, and pretty quickly, and I don't know that we need to make the change in existing repos.

**Comment by neutrinoceros** [comment]
If you are referring to #41 it was _not_ addressed yet, and this PR is actually made to eliminate the one weakness I know of that _may_ cause it.

**Comment by neutrinoceros** [comment]
I still think this has value but not enough to justify a dragging discussion. I'll close it for now.

**Pull request closed without merging**
